--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ArabSkillsNetwork/SimpleEventHandler
build-by-default: true
branches:
- master
projects:
  SimpleEventHandler:
    path: ""
    model: virion
    type: library
...
